version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --prefix function/
  build:
    commands:
      - npm run compile --prefix function/
      - sam package --template-file template.yaml --s3-bucket trading-v2-step-function-builds --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml
