AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Trading against IG

Globals:
  Function:
    Timeout: 45

Resources:
  ExecuteTrades:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 256
      Environment:
        Variables:
          DB_SCHEMA: main
          API_ACCOUNT_SECRET_NAME: IG_RODOCH_LIVE
          UNITS_AUDUSD: 1
          UNITS_EURUSD: 0.5
          UNITS_USDJPY: 0.5
          BROKER: IG
          AUDUSD_ENABLED: FALSE
          EURUSD_ENABLED: FALSE
          USDJPY_ENABLED: FALSE
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:IG_RODOCH_LIVE-CMviEg"
  ExecuteTradesDemo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 256
      Environment:
        Variables:
          DB_SCHEMA: main
          API_ACCOUNT_SECRET_NAME: IG_RODOCH_DEMO
          UNITS_AUDUSD: 1
          UNITS_EURUSD: 0.5
          UNITS_USDJPY: 0.5
          BROKER: IG
          AUDUSD_ENABLED: FALSE
          EURUSD_ENABLED: FALSE
          USDJPY_ENABLED: FALSE
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:IG_RODOCH_DEMO-YEUndG"
  ExecuteTradesRodiLive:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 512
      Environment:
        Variables:
          DB_SCHEMA: main
          API_ACCOUNT_SECRET_NAME: IG_RODI_LIVE
          UNITS_AUDUSD: 0.5
          UNITS_EURUSD: 2
          UNITS_USDJPY: 2
          BROKER: IG
          AUDUSD_ENABLED: FALSE
          EURUSD_ENABLED: FALSE
          USDJPY_ENABLED: FALSE
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:IG_RODI_LIVE-cNRS9b"
  ExecuteTradesReeceLive:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 256
      Environment:
        Variables:
          DB_SCHEMA: main
          API_ACCOUNT_SECRET_NAME: IG_REECE_LIVE
          UNITS_AUDUSD: 1
          UNITS_EURUSD: 0.5
          UNITS_USDJPY: 0.5
          BROKER: IG
          AUDUSD_ENABLED: FALSE
          EURUSD_ENABLED: FALSE
          USDJPY_ENABLED: FALSE
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:IG_REECE_LIVE-AhwdDo"
  ExecuteTradesRobertAULive:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 256
      Environment:
        Variables:
          DB_SCHEMA: main
          API_ACCOUNT_SECRET_NAME: IG_ROB_LIVE
          UNITS_AUDUSD: 1
          UNITS_EURUSD: 0.5
          UNITS_USDJPY: 0.5
          BROKER: IG
          AUDUSD_ENABLED: FALSE
          EURUSD_ENABLED: FALSE
          USDJPY_ENABLED: FALSE
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:IG_ROB_LIVE-ZPO2Cj"
  ExecuteTradesRodiCIDemo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 256
      Environment:
        Variables:
          DB_SCHEMA: main
          API_ACCOUNT_SECRET_NAME: CI_RODI_DEMO
          UNITS_AUDUSD: 1
          UNITS_EURUSD: 1
          UNITS_USDJPY: 1
          BROKER: CI
          AUDUSD_ENABLED: FALSE
          EURUSD_ENABLED: FALSE
          USDJPY_ENABLED: FALSE
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:CI_RODI_DEMO-jGJlf4"
  ExecuteTradesRodiCIProd:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 256
      Environment:
        Variables:
          DB_SCHEMA: main
          API_ACCOUNT_SECRET_NAME: CI_RODI_PROD
          UNITS_AUDUSD: 1
          UNITS_EURUSD: 1
          UNITS_USDJPY: 1
          BROKER: CI
          AUDUSD_ENABLED: FALSE
          EURUSD_ENABLED: FALSE
          USDJPY_ENABLED: FALSE
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:CI_RODI_PROD-A5M3ak"
  ExecuteTradesDanielIGProd:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 256
      Environment:
        Variables:
          DB_SCHEMA: main
          API_ACCOUNT_SECRET_NAME: IG_DANIEL_LIVE
          UNITS_AUDUSD: 0.5
          UNITS_EURUSD: 1
          UNITS_USDJPY: 1
          BROKER: IG
          AUDUSD_ENABLED: FALSE
          EURUSD_ENABLED: FALSE
          USDJPY_ENABLED: FALSE
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:IG_DANIEL_LIVE-MwMptZ"
