AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Trading against IG

Globals:
  Function:
    Timeout: 25

Resources:
  ExecuteTrades:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 256
      Environment:
        Variables:
          DB_SCHEMA: main
          IG_ACCOUNT_SECRET_NAME: IG_RODOCH_LIVE
          IG_UNITS: 0.5
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:IG_RODOCH_LIVE-CMviEg"
  ExecuteTradesDemo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Environment:
        Variables:
          DB_SCHEMA: main
          IG_ACCOUNT_SECRET_NAME: IG_RODOCH_DEMO
          IG_UNITS: 0.5
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:IG_RODOCH_DEMO-YEUndG"
  ExecuteTradesRodiLive:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 256
      Environment:
        Variables:
          DB_SCHEMA: main
          IG_ACCOUNT_SECRET_NAME: IG_RODI_LIVE
          IG_UNITS: 2
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:trading-db-secret-OyFSz9"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:ap-southeast-2:023075176548:secret:IG_RODI_LIVE-cNRS9b"
