AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Trading against IG

Globals:
  Function:
    Timeout: 15

Resources:
  TradingV2Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/built/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
