export const positions = {
  positions: [
    {
      position: {
        contractSize: 10000.0,
        createdDate: "2021/02/27 04:00:24:000",
        createdDateUTC: "2021-02-26T17:00:24",
        dealId: "DIAAAAE9K8BSEBC",
        dealReference: "9E893Y9B82844TD",
        size: 1.0,
        direction: "BUY",
        limitLevel: null as Number,
        level: 0.77182,
        currency: "USD",
        controlledRisk: false,
        stopLevel: null as Number,
        trailingStep: null as Number,
        trailingStopDistance: null as Number,
        limitedRiskPremium: null as Number,
      },
      market: {
        instrumentName: "AUD/USD Mini",
        expiry: "-",
        epic: "CS.D.AUDUSD.MINI.IP",
        instrumentType: "CURRENCIES",
        lotSize: 1.0,
        high: 0.7709,
        low: 0.7703,
        percentageChange: 0.0,
        netChange: 0.0,
        bid: 0.77032,
        offer: 0.77091,
        updateTime: "21:59:00",
        updateTimeUTC: "21:59:00",
        delayTime: 0,
        streamingPricesAvailable: true,
        marketStatus: "EDITS_ONLY",
        scalingFactor: 10000,
      },
    },
    {
      position: {
        contractSize: 10000.0,
        createdDate: "2021/02/27 04:10:25:000",
        createdDateUTC: "2021-02-26T17:10:25",
        dealId: "DIAAAAE9K9HE6BA",
        dealReference: "YK6SJLQ636T44TD",
        size: 1.0,
        direction: "BUY",
        limitLevel: null,
        level: 0.77205,
        currency: "USD",
        controlledRisk: false,
        stopLevel: null,
        trailingStep: null,
        trailingStopDistance: null,
        limitedRiskPremium: null,
      },
      market: {
        instrumentName: "AUD/USD Mini",
        expiry: "-",
        epic: "CS.D.AUDUSD.MINI.IP",
        instrumentType: "CURRENCIES",
        lotSize: 1.0,
        high: 0.7709,
        low: 0.7703,
        percentageChange: 0.0,
        netChange: 0.0,
        bid: 0.77032,
        offer: 0.77091,
        updateTime: "21:59:00",
        updateTimeUTC: "21:59:00",
        delayTime: 0,
        streamingPricesAvailable: true,
        marketStatus: "EDITS_ONLY",
        scalingFactor: 10000,
      },
    },
    {
      position: {
        contractSize: 10000.0,
        createdDate: "2021/02/27 04:20:22:000",
        createdDateUTC: "2021-02-26T17:20:22",
        dealId: "DIAAAAE9LAPHMAJ",
        dealReference: "XBZHU45YP9Z44TP",
        size: 1.0,
        direction: "BUY",
        limitLevel: null,
        level: 0.77292,
        currency: "USD",
        controlledRisk: false,
        stopLevel: null,
        trailingStep: null,
        trailingStopDistance: null,
        limitedRiskPremium: null,
      },
      market: {
        instrumentName: "AUD/USD Mini",
        expiry: "-",
        epic: "CS.D.AUDUSD.MINI.IP",
        instrumentType: "CURRENCIES",
        lotSize: 1.0,
        high: 0.7709,
        low: 0.7703,
        percentageChange: 0.0,
        netChange: 0.0,
        bid: 0.77032,
        offer: 0.77091,
        updateTime: "21:59:00",
        updateTimeUTC: "21:59:00",
        delayTime: 0,
        streamingPricesAvailable: true,
        marketStatus: "EDITS_ONLY",
        scalingFactor: 10000,
      },
    },
    {
      position: {
        contractSize: 10000.0,
        createdDate: "2021/02/27 04:40:21:000",
        createdDateUTC: "2021-02-26T17:40:21",
        dealId: "DIAAAAE9LCK64AP",
        dealReference: "BFKCVV86RA944S3",
        size: 1.0,
        direction: "BUY",
        limitLevel: null,
        level: 0.77207,
        currency: "USD",
        controlledRisk: false,
        stopLevel: null,
        trailingStep: null,
        trailingStopDistance: null,
        limitedRiskPremium: null,
      },
      market: {
        instrumentName: "AUD/USD Mini",
        expiry: "-",
        epic: "CS.D.AUDUSD.MINI.IP",
        instrumentType: "CURRENCIES",
        lotSize: 1.0,
        high: 0.7709,
        low: 0.7703,
        percentageChange: 0.0,
        netChange: 0.0,
        bid: 0.77032,
        offer: 0.77091,
        updateTime: "21:59:00",
        updateTimeUTC: "21:59:00",
        delayTime: 0,
        streamingPricesAvailable: true,
        marketStatus: "EDITS_ONLY",
        scalingFactor: 10000,
      },
    },
    {
      position: {
        contractSize: 10000.0,
        createdDate: "2021/02/27 05:00:21:000",
        createdDateUTC: "2021-02-26T18:00:21",
        dealId: "DIAAAAE9LDMA8AK",
        dealReference: "ZN9ABD63FWW44TD",
        size: 1.0,
        direction: "BUY",
        limitLevel: null,
        level: 0.77206,
        currency: "USD",
        controlledRisk: false,
        stopLevel: null,
        trailingStep: null,
        trailingStopDistance: null,
        limitedRiskPremium: null,
      },
      market: {
        instrumentName: "AUD/USD Mini",
        expiry: "-",
        epic: "CS.D.AUDUSD.MINI.IP",
        instrumentType: "CURRENCIES",
        lotSize: 1.0,
        high: 0.7709,
        low: 0.7703,
        percentageChange: 0.0,
        netChange: 0.0,
        bid: 0.77032,
        offer: 0.77091,
        updateTime: "21:59:00",
        updateTimeUTC: "21:59:00",
        delayTime: 0,
        streamingPricesAvailable: true,
        marketStatus: "EDITS_ONLY",
        scalingFactor: 10000,
      },
    },
  ],
};
